apiVersion: v1
kind: Pod
metadata:
  name: busybox-1
  labels:
    app: demo-p-to-p
spec:
  containers:
  - image: busybox
    name: busybox
    args:
      - sleep
      - "1000"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
