apiVersion: v1
kind: Pod
metadata:
  name: nginx-1
  labels:
    app: demo-p-to-p
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
