apiVersion: v1
kind: Pod
metadata:
  name: nginx-busybox
  labels:
    app: demo-c-to-c
spec:
  containers:
  - image: busybox
    name: busybox
    args:
      - sleep
      - "1000"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
