apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    app: demo-p-to-s
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
        name: http-web-svc
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: demo-p-to-s
  ports:
  - name: http-web-svc
    protocol: TCP
    port: 80
    targetPort: http-web-svc